### ISSUE TITLE
No tickets provided for attachment retrieval.

### ISSUE THREAD

**Issue by binarytemple** [basho/zdgrab#2]
As of today, I get that response when attempting to retrieve a ticket e.g: 

```
zdgrab -t 10541 
No tickets provided for attachment retrieval.
```

**Comment by binarytemple** [comment]
I updated to the latest version using `pip install --upgrade` and get this message : 
```
[~%]zdgrab -t 10635
Traceback (most recent call last):
  File "/usr/local/bin/zdgrab", line 7, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/zdgrab/zdgrab.py", line 213, in main
    zdeskcfg.call(zdgrab, section='zdgrab')
  File "/usr/local/lib/python2.7/site-packages/zdeskcfg.py", line 151, in call
    return plac_ini.call(obj, config=config, default_section=section, eager=eager)
  File "/usr/local/lib/python2.7/site-packages/plac_ini.py", line 156, in call
    cmd, result = argparser.consume(arglist)
  File "/usr/local/lib/python2.7/site-packages/plac_core.py", line 195, in consume
    return cmd, self.func(*(args + varargs + extraopts), **kwargs)
  File "<string>", line 6, in _wrapper_
  File "/usr/local/lib/python2.7/site-packages/zdgrab/zdgrab.py", line 190, in zdgrab
    response, content = zd.client.request(attachment['content_url'], headers=headers)
  File "/usr/local/lib/python2.7/site-packages/httplib2/__init__.py", line 1608, in request
    (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirection
s, cachekey)
  File "/usr/local/lib/python2.7/site-packages/httplib2/__init__.py", line 1403, in _request
    redirections=redirections - 1)
  File "/usr/local/lib/python2.7/site-packages/httplib2/__init__.py", line 1608, in request
    (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirection
s, cachekey)
  File "/usr/local/lib/python2.7/site-packages/httplib2/__init__.py", line 1403, in _request
    redirections=redirections - 1)
  File "/usr/local/lib/python2.7/site-packages/httplib2/__init__.py", line 1608, in request
    (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirection
s, cachekey)
  File "/usr/local/lib/python2.7/site-packages/httplib2/__init__.py", line 1350, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "/usr/local/lib/python2.7/site-packages/httplib2/__init__.py", line 1278, in _conn_request
    raise ServerNotFoundError("Unable to find the server at %s" % conn.host)
httplib2.ServerNotFoundError: Unable to find the server at support.sl.attcompute.com
```

**Comment by binarytemple** [comment]
Problem is a dead server on Zendesk side
